# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod Properties
mod_version=1.0.1
maven_group=com.ltcg.modmenuwebaddon
archives_base_name=modmenu-web-addon
mod_id=modmenuwebaddon
mod_name=Mod Menu Web Addon
mod_license=MIT

# Loader tooling
loader_version=0.19.5
loom_version=1.15-SNAPSHOT

# --- Minecraft 26.2 ---
minecraft_version=26.3
fabric_version=0.161.0+26.3
modmenu_version=21.0.0
